import Head from "next/head";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../utils/apollo-client";
import {
  CountrylistDocument,
  CountrylistQuery,
} from "../codegen/generated/graphql";
import { Container, Header } from "../components";

interface Props {
  countries: CountrylistQuery["countries"];
}

const Home = ({ countries }: Props) => {
  return (
    <div>
      <Head>
        <title>E-comm</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

/*export async function getStaticProps() {
  const { data } =
    await client.query<CountrylistQuery>({
      query: CountrylistDocument,
    });

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}*/

export default Home;
