import type { NextPage } from "next";
import Head from "next/head";
import {
  BestSeller,
  Featured,
  Navbar,
} from "../components";
import Header from "../components/Header/Header";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yunus İNAN</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Navbar></Navbar>
      <Featured></Featured>
      <BestSeller></BestSeller>
    </div>
  );
};

export default Home;
